<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_VFD" Id="{3dc147eb-3dde-4052-8db8-ee0200a73c1f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_VFD
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_VFD">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>