<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{04ba039b-795a-46fa-8d67-a13d131c6641}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMachine				: FB_Machine;
	Run AT %Q* : BOOL := TRUE;
	ErrorAcknowledge AT %Q* : BOOL;
	errorReset AT %Q* : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMachine();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>